# Generated by Django 4.1.1 on 2022-09-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=200)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='plant.plant')),
            ],
        ),
    ]
